
version: '3'

services:
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
  db:
    image: postgres:latest

    ports:
      - "5432:5432"
    container_name: admin-skeleton-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: someroot
      POSTGRES_DB: admin-skeleton
